void printHisto(Histo& histo){

	TDirectory* currentDir=gDirectory;
	TFile* fout = new TFile("out.root","RECREATE"); 

    TCanvas *cmt = new TCanvas("cmt", "t mass",1200,1000);
	cmt->Divide(4,2);
	//top1
	cmt->cd(1);
	histo.hmt1_star_good0->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt1_star_good0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_good0->SetFillStyle(1001);
    histo.hmt1_star_good0->SetLineColor(1);
	histo.hmt1_star_good0->Draw("histe");
	cmt->cd(2);
	histo.hmt1_star_bad0->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt1_star_bad0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_bad0->SetFillStyle(1001);
    histo.hmt1_star_bad0->SetLineColor(1);
    histo.hmt1_star_bad0->Draw("histe");
    cmt->cd(3);
    histo.hmt1_star_good1->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt1_star_good1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_good1->SetFillStyle(1001);
    histo.hmt1_star_good1->SetLineColor(1);
    histo.hmt1_star_good1->Draw("histe");
    cmt->cd(4);
    histo.hmt1_star_bad1->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt1_star_bad1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_bad1->SetFillStyle(1001);
    histo.hmt1_star_bad1->SetLineColor(1);
    histo.hmt1_star_bad1->Draw("histe");
    //top2
	cmt->cd(5);
	histo.hmt2_star_good0->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star_good0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_good0->SetFillStyle(1001);
    histo.hmt2_star_good0->SetLineColor(1);
    histo.hmt2_star_good0->Draw("histe");
	cmt->cd(6);
    histo.hmt2_star_bad0->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star_bad0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_bad0->SetFillStyle(1001);
    histo.hmt2_star_bad0->SetLineColor(1);
    histo.hmt2_star_bad0->Draw("histe");
    cmt->cd(7);
    histo.hmt2_star_good1->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star_good1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_good1->SetFillStyle(1001);
    histo.hmt2_star_good1->SetLineColor(1);
    histo.hmt2_star_good1->Draw("histe");
    cmt->cd(8);
    histo.hmt2_star_bad1->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star_bad1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_bad1->SetFillStyle(1001);
    histo.hmt2_star_bad1->SetLineColor(1);
    histo.hmt2_star_bad1->Draw("histe");
    cmt->Write();
    delete cmt;

    TCanvas *cmt0 = new TCanvas("cmt0", "t mass",1200,600);
	cmt0->Divide(3,2);
	cmt0->cd(1);
	histo.hmt1_star->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt1_star->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star->SetFillStyle(1001);
    histo.hmt1_star->SetLineColor(1);
	histo.hmt1_star->Draw("histe");
	cmt0->cd(2);
	histo.hmt1_star_good0->Draw("histe");
	cmt0->cd(3);
	histo.hmt1_star_bad0->Draw("histe");
	cmt0->cd(4);
	histo.hmt2_star->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star->SetFillStyle(1001);
    histo.hmt2_star->SetLineColor(1);
	histo.hmt2_star->Draw("histe");
	cmt0->cd(5);
	histo.hmt2_star_good0->Draw("histe");
	cmt0->cd(6);
	histo.hmt2_star_bad0->Draw("histe");
	cmt0->Write();
	delete cmt0;

	TCanvas *cmt1 = new TCanvas("cmt1", "t mass",1200,600);
	cmt1->Divide(3,2);
	cmt1->cd(1);
	histo.hmt1_star_bad0->Draw("histe");
	cmt1->cd(2);
	histo.hmt1_star_good1->Draw("histe");
	cmt1->cd(3);
	histo.hmt1_star_bad1->Draw("histe");
	cmt1->cd(4);
	histo.hmt2_star_bad0->Draw("histe");
	cmt1->cd(5);
	histo.hmt2_star_good1->Draw("histe");
	cmt1->cd(6);
	histo.hmt2_star_bad1->Draw("histe");
	cmt1->Write();
	delete cmt1;

	TCanvas *cmt2 = new TCanvas("cmt2", "t mass",1200,600);
	cmt2->Divide(3,2);
	cmt2->cd(1);
	histo.hmt1_star->Draw("histe");
	cmt2->cd(2);
	histo.hmt1_star_good->GetXaxis()->SetTitle("m_{bb}");
	histo.hmt1_star_good->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_good->SetFillStyle(1001);
    histo.hmt1_star_good->SetLineColor(1);
	histo.hmt1_star_good->Draw("histe");
	cmt2->cd(3);
	histo.hmt1_star_bad->GetXaxis()->SetTitle("m_{bb}");
	histo.hmt1_star_bad->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt1_star_bad->SetFillStyle(1001);
    histo.hmt1_star_bad->SetLineColor(1);
	histo.hmt1_star_bad->Draw("histe");
	cmt2->cd(4);
	histo.hmt2_star->Draw("histe");
	cmt2->cd(5);
	histo.hmt2_star_good->GetXaxis()->SetTitle("m_{bb}");
	histo.hmt2_star_good->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_good->SetFillStyle(1001);
    histo.hmt2_star_good->SetLineColor(1);
	histo.hmt2_star_good->Draw("histe");
	cmt2->cd(6);
	histo.hmt2_star_bad->GetXaxis()->SetTitle("m_{bb}");
	histo.hmt2_star_bad->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmt2_star_bad->SetFillStyle(1001);
    histo.hmt2_star_bad->SetLineColor(1);
	histo.hmt2_star_bad->Draw("histe");
	cmt2->Write();
	delete cmt2;

    TCanvas *cmw = new TCanvas("cmw", "W mass",1200,1000);
	cmw->Divide(4,2);
	//top1
	cmw->cd(1);
	histo.hmw1_star_good0->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw1_star_good0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_good0->SetFillStyle(1001);
    histo.hmw1_star_good0->SetLineColor(1);
	histo.hmw1_star_good0->Draw("histe");
	cmw->cd(2);
	histo.hmw1_star_bad0->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw1_star_bad0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_bad0->SetFillStyle(1001);
    histo.hmw1_star_bad0->SetLineColor(1);
    histo.hmw1_star_bad0->Draw("histe");
    cmw->cd(3);
    histo.hmw1_star_good1->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw1_star_good1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_good1->SetFillStyle(1001);
    histo.hmw1_star_good1->SetLineColor(1);
    histo.hmw1_star_good1->Draw("histe");
    cmw->cd(4);
    histo.hmw1_star_bad1->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw1_star_bad1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_bad1->SetFillStyle(1001);
    histo.hmw1_star_bad1->SetLineColor(1);
    histo.hmw1_star_bad1->Draw("histe");
    //top2
	cmw->cd(5);
	histo.hmw2_star_good0->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw2_star_good0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_good0->SetFillStyle(1001);
    histo.hmw2_star_good0->SetLineColor(1);
    histo.hmw2_star_good0->Draw("histe");
	cmw->cd(6);
    histo.hmw2_star_bad0->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw2_star_bad0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_bad0->SetFillStyle(1001);
    histo.hmw2_star_bad0->SetLineColor(1);
    histo.hmw2_star_bad0->Draw("histe");
    cmw->cd(7);
    histo.hmw2_star_good1->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw2_star_good1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_good1->SetFillStyle(1001);
    histo.hmw2_star_good1->SetLineColor(1);
    histo.hmw2_star_good1->Draw("histe");
    cmw->cd(8);
    histo.hmw2_star_bad1->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw2_star_bad1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_bad1->SetFillStyle(1001);
    histo.hmw2_star_bad1->SetLineColor(1);
    histo.hmw2_star_bad1->Draw("histe");
    cmw->Write();
    delete cmw;

    TCanvas *cmw0 = new TCanvas("cmw0", "t mass",1200,600);
	cmw0->Divide(3,2);
	cmw0->cd(1);
	histo.hmw1_star->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw1_star->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star->SetFillStyle(1001);
    histo.hmw1_star->SetLineColor(1);
	histo.hmw1_star->Draw("histe");
	cmw0->cd(2);
	histo.hmw1_star_good0->Draw("histe");
	cmw0->cd(3);
	histo.hmw1_star_bad0->Draw("histe");
	cmw0->cd(4);
	histo.hmw2_star->GetXaxis()->SetTitle("m_{jj}");
	histo.hmw2_star->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star->SetFillStyle(1001);
    histo.hmw2_star->SetLineColor(1);
	histo.hmw2_star->Draw("histe");
	cmw0->cd(5);
	histo.hmw2_star_good0->Draw("histe");
	cmw0->cd(6);
	histo.hmw2_star_bad0->Draw("histe");
	cmw0->Write();
	delete cmw0;

	TCanvas *cmw1 = new TCanvas("cmw1", "t mass",1200,600);
	cmw1->Divide(3,2);
	cmw1->cd(1);
	histo.hmw1_star_bad0->Draw("histe");
	cmw1->cd(2);
	histo.hmw1_star_good1->Draw("histe");
	cmw1->cd(3);
	histo.hmw1_star_bad1->Draw("histe");
	cmw1->cd(4);
	histo.hmw2_star_bad0->Draw("histe");
	cmw1->cd(5);
	histo.hmw2_star_good1->Draw("histe");
	cmw1->cd(6);
	histo.hmw2_star_bad1->Draw("histe");
	cmw1->Write();
	delete cmw1;

	TCanvas *cmw2 = new TCanvas("cmw2", "t mass",1200,600);
	cmw2->Divide(3,2);
	cmw2->cd(1);
	histo.hmw1_star->Draw("histe");
	cmw2->cd(2);
	histo.hmw1_star_good->GetXaxis()->SetTitle("m_{bb}");
	histo.hmw1_star_good->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_good->SetFillStyle(1001);
    histo.hmw1_star_good->SetLineColor(1);
	histo.hmw1_star_good->Draw("histe");
	cmw2->cd(3);
	histo.hmw1_star_bad->GetXaxis()->SetTitle("m_{bb}");
	histo.hmw1_star_bad->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw1_star_bad->SetFillStyle(1001);
    histo.hmw1_star_bad->SetLineColor(1);
	histo.hmw1_star_bad->Draw("histe");
	cmw2->cd(4);
	histo.hmw2_star->Draw("histe");
	cmw2->cd(5);
	histo.hmw2_star_good->GetXaxis()->SetTitle("m_{bb}");
	histo.hmw2_star_good->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_good->SetFillStyle(1001);
    histo.hmw2_star_good->SetLineColor(1);
	histo.hmw2_star_good->Draw("histe");
	cmw2->cd(6);
	histo.hmw2_star_bad->GetXaxis()->SetTitle("m_{bb}");
	histo.hmw2_star_bad->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmw2_star_bad->SetFillStyle(1001);
    histo.hmw2_star_bad->SetLineColor(1);
	histo.hmw2_star_bad->Draw("histe");
	cmw2->Write();
	delete cmw2;

    TCanvas *cmh = new TCanvas("cmh", "H mass",800,600);
	cmh->Divide(4,1);
	cmh->cd(1);
	histo.hmh_star_good0->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_good0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_good0->SetFillStyle(1001);
    histo.hmh_star_good0->SetLineColor(1);
    histo.hmh_star_good0->Draw("histe");
	cmh->cd(2);
	histo.hmh_star_bad0->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_bad0->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_bad0->SetFillStyle(1001);
    histo.hmh_star_bad0->SetLineColor(1);
    histo.hmh_star_bad0->Draw("histe");
    cmh->cd(3);
    histo.hmh_star_good1->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_good1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_good1->SetFillStyle(1001);
    histo.hmh_star_good1->SetLineColor(1);
    histo.hmh_star_good1->Draw("histe");
    cmh->cd(4);
    histo.hmh_star_bad1->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_bad1->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_bad1->SetFillStyle(1001);
    histo.hmh_star_bad1->SetLineColor(1);
    histo.hmh_star_bad1->Draw("histe");
    cmh->Write();
    delete cmh;

    TCanvas *cmh0 = new TCanvas("cmh0", "H mass",1000,600);
	cmh0->Divide(3,1);
	cmh0->cd(1);
	histo.hmh_star->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star->SetFillStyle(1001);
    histo.hmh_star->SetLineColor(1);
    histo.hmh_star->Draw("histe");
	cmh0->cd(2);
    histo.hmh_star_good0->Draw("histe");
	cmh0->cd(3);
    histo.hmh_star_bad0->Draw("histe");
    cmh0->Write();
    delete cmh0;

    TCanvas *cmh1 = new TCanvas("cmh1", "H mass",1000,600);
	cmh1->Divide(3,1);
	cmh1->cd(1);
    histo.hmh_star_bad0->Draw("histe");
	cmh1->cd(2);
    histo.hmh_star_good1->Draw("histe");
	cmh1->cd(3);
    histo.hmh_star_bad1->Draw("histe");
    cmh1->Write();
    delete cmh1;

    TCanvas *cmh2 = new TCanvas("cmh2", "H mass",1000,600);
	cmh2->Divide(3,1);
	cmh2->cd(1);
    histo.hmh_star->Draw("histe");
	cmh2->cd(2);
	histo.hmh_star_good->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_good->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_good->SetFillStyle(1001);
    histo.hmh_star_good->SetLineColor(1);
    histo.hmh_star_good->Draw("histe");
	cmh2->cd(3);
	histo.hmh_star_bad->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star_bad->SetFillColorAlpha(kAzure+7, 0.4);
    histo.hmh_star_bad->SetFillStyle(1001);
    histo.hmh_star_bad->SetLineColor(1);
    histo.hmh_star_bad->Draw("histe");
    cmh2->Write();
    delete cmh2;

    TCanvas *cm_comparison = new TCanvas("cm_comparison", "mass",600,800);
    cm_comparison->Divide(2,3);
    cm_comparison->cd(1);
    histo.hmt1_star_good->GetXaxis()->SetTitle("m_{bjj}");
    histo.hmt1_star_good->SetFillColor(kRed);
    histo.hmt1_star_good->SetFillStyle(3004);
	histo.hmt1_star_good->SetLineColor(1);
	histo.hmt1_star_good->Draw("histe");
	histo.hmt1_star->SetFillColor(kWhite);
    histo.hmt1_star->SetFillStyle(1001);
    histo.hmt1_star->SetLineColor(kBlue);
    histo.hmt1_star->Draw("histe same");
	cm_comparison->cd(2);
	histo.hmt2_star_good->SetFillColor(kRed);
    histo.hmt2_star_good->SetFillStyle(3004);
	histo.hmt2_star_good->SetLineColor(1);
	histo.hmt2_star_good->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmt2_star_good->Draw("histe");
	histo.hmt2_star->SetFillColor(kWhite);
	histo.hmt2_star->SetLineColor(kBlue);
    histo.hmt2_star->Draw("histe same");   
	cm_comparison->cd(3);
	histo.hmw1_star_good->SetFillColor(kRed);
    histo.hmw1_star_good->SetFillStyle(3004);
	histo.hmw1_star_good->SetLineColor(1);
	histo.hmw1_star_good->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmw1_star_good->Draw("histe");
	histo.hmw1_star->SetFillColor(kWhite);
	histo.hmw1_star->SetLineColor(kBlue);
    histo.hmw1_star->Draw("histe same");
	cm_comparison->cd(4);
	histo.hmw2_star_good->SetFillColor(kRed);
    histo.hmw2_star_good->SetFillStyle(3004);
	histo.hmw2_star_good->SetLineColor(1);
	histo.hmw2_star_good->GetXaxis()->SetTitle("m_{bjj}");
	histo.hmw2_star_good->Draw("histe");
	histo.hmw2_star->SetFillColor(kWhite);
	histo.hmw2_star->SetLineColor(kBlue);
    histo.hmw2_star->Draw("histe same");
	cm_comparison->cd(5);
	histo.hmh_star->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_star->SetFillColor(kWhite);
	histo.hmh_star->SetLineColor(kBlue);
	histo.hmh_star->Draw("histe");
    histo.hmh_star_good->SetFillColor(kRed);
    histo.hmh_star_good->SetFillStyle(3004);
	histo.hmh_star_good->SetLineColor(1);
	histo.hmh_star_good->Draw("histe same");
	cm_comparison->cd(6);
	histo.hmh_gen->GetXaxis()->SetTitle("m_{bb}");
	histo.hmh_gen->SetFillStyle(3004);
	histo.hmh_gen->SetFillColor(kRed);
	histo.hmh_gen->SetLineColor(1);
	histo.hmh_gen->Draw("histe");
	histo.hmh_dr->SetLineColor(kBlue);
	histo.hmh_dr->Draw("histe same");
    cm_comparison->Write();
    delete cm_comparison;

    TCanvas *ch_match0 = new TCanvas("ch_match0", "H",800,600);
    histo.hmh_1match->GetXaxis()->SetTitle("m_{bb}");
    histo.hmh_1match->SetLineColor(kBlue);
    histo.hmh_1match->Draw("histe");
    histo.hmh_2match->SetLineColor(kRed);
    histo.hmh_2match->Draw("histe same");
    histo.hmh_0match->SetLineColor(kBlack);
    histo.hmh_0match->Draw("histe same");
    TLegend *leg = new TLegend(0.6,0.6,0.8,0.8);
	leg->AddEntry(histo.hmh_2match,"2 match");
    leg->AddEntry(histo.hmh_1match,"1 match");
    leg->AddEntry(histo.hmh_0match,"0 match");
    leg->Draw("same");
    ch_match0->Write();
    delete ch_match0;

    TCanvas *ch_match1 = new TCanvas("ch_match1", "H",800,600);
    histo.hmh_1match1->SetLineColor(kBlue);
    histo.hmh_1match1->Draw("histe");
    histo.hmh_1match1->GetXaxis()->SetTitle("m_{bb}");
    histo.hmh_2match1->SetLineColor(kRed);
    histo.hmh_2match1->Draw("histe same");
    histo.hmh_0match1->SetLineColor(kBlack);
    histo.hmh_0match1->Draw("histe same");
    TLegend *leg1 = new TLegend(0.6,0.6,0.8,0.8);
	leg1->AddEntry(histo.hmh_2match1,"2 match");
    leg1->AddEntry(histo.hmh_1match1,"1 match");
    leg1->AddEntry(histo.hmh_0match1,"0 match");
    leg1->Draw("same");
    ch_match1->Write();
    delete ch_match1;

    TCanvas *ct2D = new TCanvas("ct2D", "t mass",800,600);
    ct2D->Divide(2,1);
    ct2D->cd(1);
    histo.ht2D_good->Draw("COLZ");
    ct2D->cd(2);
    histo.ht2D_bad->Draw("COLZ");
    ct2D->Write();
    delete ct2D;

    delete fout;
	return;
}